### ISSUE TITLE
HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by abeburnett** [googleads/googleads-python-lib#181] opened 2017-02-14 22:32 UTC
Hi there,

I'm brand new to the AdWords API, so it's likely I'm submitting (somehow) a malformed request (given the error). I'm hoping I can have some assistance troubleshooting. I've setup my googleads.yaml with my developer token, client_id, client_secret, and refresh_token, and I'm just trying to run one of the example scripts which retrieves keywords that are related to a given keyword. I'm running the Python 3 version, on a Mac (10.12.3). 

It's breaking at the `targeting_idea_service.get(selector)` section.

Here's the error I'm getting (though I don't see see anything useful in it):

```
HTTPError: HTTP Error 500: Internal Server Error
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-52-c75b0d0083fa> in <module>()
     74   adwords_client = adwords.AdWordsClient.LoadFromStorage()
     75 
---> 76   main(adwords_client)
<ipython-input-52-c75b0d0083fa> in main(client)
     48   more_pages = True
     49   while more_pages:
---> 50     page = targeting_idea_service.get(selector)
     51 
     52     # Display results.
/usr/local/lib/python3.6/site-packages/googleads/common.py in MakeSoapRequest(*args)
    698       try:
    699         return soap_service_method(
--> 700             *[_PackForSuds(arg, self.suds_client.factory) for arg in args])
    701       except suds.WebFault as e:
    702         _logger.error('Server raised fault in response.')
/usr/local/lib/python3.6/site-packages/suds/client.py in __call__(self, *args, **kwargs)
    519         client = clientclass(self.client, self.method)
    520         try:
--> 521             return client.invoke(args, kwargs)
    522         except WebFault as e:
    523             if self.faults():
/usr/local/lib/python3.6/site-packages/suds/client.py in invoke(self, args, kwargs)
    579             timer)
    580         timer.start()
--> 581         result = self.send(soapenv)
    582         timer.stop()
    583         metrics.log.debug("method '%s' invoked: %s", self.method.name, timer)
/usr/local/lib/python3.6/site-packages/suds/client.py in send(self, soapenv)
    611             timer = metrics.Timer()
    612             timer.start()
--> 613             reply = self.options.transport.send(request)
    614             timer.stop()
    615             metrics.log.debug('waited %s on server reply', timer)
/usr/local/lib/python3.6/site-packages/googleads/util.py in PatchedHttpTransportSend(self, request)
     96       request.headers.update(u2request.headers)
     97       suds.transport.http.log.debug('sending:\n%s', request)
---> 98       try:
     99         fp = self.u2open(u2request)
    100       except urllib.error.HTTPError as e:
/usr/local/lib/python3.6/site-packages/suds/transport/http.py in u2open(self, u2request)
    130             socket.setdefaulttimeout(tm)
    131             return url.open(u2request)
--> 132         return url.open(u2request, timeout=tm)
    133 
    134     def u2opener(self):
/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py in open(self, fullurl, data, timeout)
    530         for processor in self.process_response.get(protocol, []):
    531             meth = getattr(processor, meth_name)
--> 532             response = meth(req, response)
    533 
    534         return response
/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py in http_response(self, request, response)
    640         if not (200 <= code < 300):
    641             response = self.parent.error(
--> 642                 'http', request, response, code, msg, hdrs)
    643 
    644         return response
/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py in error(self, proto, *args)
    568         if http_err:
    569             args = (dict, 'default', 'http_error_default') + orig_args
--> 570             return self._call_chain(*args)
    571 
    572 # XXX probably also want an abstract factory that knows when it makes
/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    502         for handler in handlers:
    503             func = getattr(handler, meth_name)
--> 504             result = func(*args)
    505             if result is not None:
    506                 return result
/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):
HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by abeburnett** [comment] 2017-02-14 22:39
https://github.com/googleads/googleads-python-lib/issues/181

**Comment by abeburnett** [comment] 2017-02-14 22:40
For others who run into the 500 error with the newest versions, try the workaround of installing (`pip uninstall googleads` && `pip install "googleads==4.7.0"`)

**Comment by msaniscalchi** [comment] 2017-02-14 22:44
Hello, thanks for the report!

How recently have you updated your installation? A similar issue was reported in 5.0.0, which should have been fixed in 5.1.0.

**Comment by abeburnett** [comment] 2017-02-14 22:52
I just made sure I was updated to 5.1.0 before trying again, and it didn't
work for me. 😞

**Comment by msaniscalchi** [comment] 2017-02-14 23:04
Could you send over a trivialized snippet of code that reproduces the issue for you? I attempted to reproduce, but did get back the expected WebFault indicating an issue in the selector.

**Comment by msaniscalchi** [comment] 2017-03-02 00:08
I'll close this since it seems like you figured it out on your own, but feel free to re-open if I can still assist with this.

**Closed by msaniscalchi** 2017-03-02 00:08 UTC
