### ISSUE TITLE
ValueError: check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED

### ISSUE THREAD

**Issue by Bobspadger** [googleads/googleads-python-lib#164] opened 2016-11-30 13:26 UTC
https://github.com/GoogleCloudPlatform/httplib2shim/issues/4

**Comment by msaniscalchi** [comment] 2016-11-30 15:27
Hello,

We've had [issues like this](https://github.com/googleads/googleads-python-lib/issues/53) in the past. Using a fresh Python installation should resolve the issue.

Regards,
Mark

**Comment by Bobspadger** [comment] 2016-11-30 15:42
Hi Mark

I have, its a fresh install into a virtual environment.
I've checked httplib versions etc (they are the same as my mac)

I don't think this is truly a fix.

Cheers

Alex

**Comment by Bobspadger** [comment] 2016-11-30 22:47
As an update, here's what I've tried.

1. Reinstalling python3 on 14.0.4 -> Still same error.
2. Clean install of ubuntu 14.0.4 and all requirements -> Still same error.
3. Run on 16.0.4 with python3.5 -> Works.

So, I don't think its as simple as 'reinstall python' as a clean install also fails.

**Comment by msaniscalchi** [comment] 2016-11-30 23:10
Thanks for the update, I'll look into this.

It's been some time since I last saw this issue, but if I recall correctly, one potential cause is whether the installed version of Python was compiled with SSL support.

**Comment by msaniscalchi** [comment] 2017-03-31 21:15
I made another attempt to reproduce on a fresh VM running 14.0.4, using Python 3. Still no luck, unfortunately.

I'm pretty confident that this is an environment-related issue that is beyond the scope of this library. If you can find a way to reliably reproduce, I'll continue digging into this. Barring that though, there's not much I can do, so I will close this for now.

**Closed by msaniscalchi** 2017-03-31 21:15 UTC
