### ISSUE TITLE
Upgrade Version API v201802 error - cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by Bafrice22** [googleads/googleads-python-lib#291] opened 2018-06-11 16:33 UTC
Hello,

We are currently using version **v201710** of the Adwords api and would like to upgrade to version **v201802**.

We are using python version 3.5 and googleads version 12.1.0

We are facing the following issue when using this piece of code :

service = client.GetService('CustomerService', version='v201802')
accounts = service.getCustomers()
> error: **cannot use a string pattern on a bytes-like object**

The error seems clear but it used to work with the previous version and I did not manage to find how the response changed.

Best Regards,

**Comment by msaniscalchi** [comment] 2018-06-11 18:00
Hello,

Thanks for the report! I've attempted to reproduce in Python 2 and 3 with both suds / zeep used as the SOAP client, and with logging enabled. I have not yet been able to reproduce your reported error, but it sounds potentially like what one might see when using `re` with a unicode string pattern on a byte string.

I may be able to get some additional clues on the cause if you could provide a full stacktrace.

Regards,
Mark

**Comment by msaniscalchi** [comment] 2018-06-21 20:41
Closing because this is not actionable as-is, but feel free to reopen if this is reproducible.

**Closed by msaniscalchi** 2018-06-21 20:41 UTC
Labels: P2
