### ISSUE TITLE
"ImportError: No module named lxml.builder"

### ISSUE THREAD

**Issue by STANAPI** [googleads/googleads-python-lib#373] opened 2019-02-14 06:11 UTC
I was using the old version, so need to migrate to the latest version. 

I have downloaded the entire folder and tried to run the "adwords_test.py", but it gives me the error message:

"ImportError: No module named lxml.builder"

Do I need to install any other library?

**Comment by BenRKarl** [comment] 2019-03-14 17:41
@STANAPI thanks for this question. I'm going to close this issue because it appears to be a duplicate of this one: https://github.com/googleads/googleads-python-lib/issues/372

Feel free to reopen it if that's not the case.

**Closed by BenRKarl** 2019-03-14 17:41 UTC
