### ISSUE TITLE
dates missing for adgroup performance report

### ISSUE THREAD

**Issue by ildengemil** [googleads/googleads-python-lib#362] opened 2019-01-07 17:14 UTC
Hello! There are dates missing for certain adgroup IDs, for example, there is data for:

12.11.2018 data available
13.11.2018 data available
14.11.2018 data MISSING
15.11.2018 on wards data available

But when we compare data with the UI, we have impression data there. Also it happens for low volume adgroups but still it creates a hassle for our reporting/models.

We have also upgraded to the latest client library 15.0.1.
Could you please help out with this bug?

**Comment by BenRKarl** [comment] 2019-01-10 22:10
Hi @ildengemil - 

Thanks for creating this issue. I'm working on investigating it now and will share a resolution here as soon as possible.

**Comment by BenRKarl** [comment] 2019-01-22 22:48
Closing this out because the issue was determined to intended behavior. By default AdGroupPerformanceReport will not display ads or groups that have zero impressions. It's possible to display empty results by setting the `include_zero_impressions` flag to `True`, for [example](https://github.com/googleads/googleads-python-lib/blob/cd707dc897b93cf1bbb19355f7424e7834e7fb55/examples/adwords/v201802/reporting/download_criteria_report_with_awql.py#L51).

**Closed by BenRKarl** 2019-01-22 22:48 UTC
