### ISSUE TITLE
'int' object has no attribute 'get'

### ISSUE THREAD

**Issue by peter-marshall** [googleads/googleads-python-lib#333] opened 2018-10-12 12:39 UTC
Possibly related to #332, hope this helps.

I get the error `'int' object has no attribute 'get'`.

This happens when I provide some credentials pasted from a previous project. These credentials are valid OAuth2 credentials for the other project. But they're from a Google account with no attached Ad Manager account.

**Comment by peter-marshall** [comment] 2018-10-12 16:03
Looks like it happens when:
- the OAuth2 client ID and client secret are valid
- the refresh token for above is maybe valid in some context, but doesn't offer the Ad Manager scope.

I generated a new refresh token (clicking to approve the Ad Manager scope), signed in with that refresh token and the error went away.

**Comment by peter-marshall** [comment] 2018-10-14 13:05
Further info:

The error only happened when I called `WaitForReport()`.

I think it was either due to:
- The refresh token being insufficient to allow access, or
- Invalid scope. The script used to pass `u'https://www.googleapis.com/auth/ad_manager'` and I changed it to `oauth2.GetAPIScope('ad_manager')`

**Comment by drorbar** [comment] 2018-11-19 14:38
This problem also happening to me.
Here is the relevant stacktrace: 

`
  page = managed_customer_service.get(selector)
  File "/usr/local/lib/python2.7/site-packages/googleads/common.py", line 1382, in MakeSoapRequest
    underlying_exception, self.zeep_client.wsdl.types)
  File "/usr/local/lib/python2.7/site-packages/zeep/xsd/elements/element.py", line 92, in parse
    instance_type = qname_attr(xmlelement, xsi_ns('type'))
  File "/usr/local/lib/python2.7/site-packages/zeep/utils.py", line 10, in qname_attr
    value = node.get(attr_name)
GeneralUnhandledError: 'int' object has no attribute 'get'`

As far as I can understand this problem happened when the code run the function:
return soap_service_method(*packed_args, _soapheaders=soap_headers)['body']['rval'] from `/usr/local/lib/python2.7/site-packages/googleads/common.py` 
I get the exeption Fault('Unknown fault occured') and the details of this error is: 
`
'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<HTML>\n<HEAD>\n<TITLE>Unauthorized</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Unauthorized</H1>\n<H2>Error 401</H2>\n</BODY>\n</HTML>\n'`

Than the code try to parse the error of the zeep fault: The underlying_exception is -1 and i think this causes this line to failed (1393): `fault = fault_type.parse(underlying_exception, self.zeep_client.wsdl.types)`, it expected the underlying_exception to be xml obj but it's an integer (-1)

**Comment by drorbar** [comment] 2018-11-19 15:46
I did a small PR to make sure that no matter what the lib will return a googleads type error with the information about the original error.
If there are some fixes\changes you think are better just tell me - but for now I needed something fast that will work

https://github.com/googleads/googleads-python-lib/pull/348

**Comment by christopherseeley** [comment] 2024-03-28 00:13
Duplicate of #451

**Closed by christopherseeley** 2024-03-28 00:13 UTC
