### ISSUE TITLE
RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>

### ISSUE THREAD

**Issue by Matthew-Horrocks-MediaCom** [googleads/googleads-python-lib#315] opened 2018-08-07 16:13 UTC
I've recently updated my python scripts from python 2 to python 3. When going through codes Id already written I kept getting an error when I ever I run the line:

`page_service = client.GetService(service, version='v201806')`

However when I run the same script without changing anything in python 2 it gets no errors. This error only occurs when I am trying to call a service and not when I'm calling a report. I have also tried using example codes from this repo but encounter the same error.

The Error is:
  File "C:\Users\Matthew.Horrocks\AppData\Local\Continuum\anaconda3\lib\imp.py", line 271, in find_module
    raise RuntimeError("'path' must be None or a list, not {}".format(type(path)))

RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>

**Comment by msaniscalchi** [comment] 2018-08-07 20:13
Hello Matthew,

Thanks for the report! I'm unable to reproduce this issue, but do see that the underlying error doesn't appear to be in this library. I have seen a similar issue in a [previous report](https://github.com/googleads/googleads-python-lib/issues/274), which was ultimately related to the IDE being used.

Regards,
Mark

**Comment by msaniscalchi** [comment] 2018-08-22 15:06
Hello Matthew,

I'll close this bug now with the expectation that my previous reply helped resolve this issue, feel free to reopen if that there are issues relating to this client library that I can assist you with.

Regards,
Mark

**Closed by msaniscalchi** 2018-08-22 15:06 UTC
