### ISSUE TITLE
Is v23.0.1 compatible with Python 3.8.2? 

### ISSUE THREAD

**Issue by saushettevite** [googleads/googleads-python-lib#462] opened 2020-05-11 18:38 UTC
I am getting this error - 
RuntimeError: sqlite3 module is required for the SqliteCache

Not sure what needs to be changed to not let this error occur. I am trying to upgrade to a higher version of Admanager API, above v201905.

**Comment by msaniscalchi** [comment] 2022-12-15 02:43
I'm closing this out because it is rather dated, but to answer the question I've verified that we continue to support Python 3.7 or higher, up to 3.11.1 as of this writing.

The error mentioned above is not reproducible, although could plausibly be related to using [SqliteCache](https://docs.python-zeep.org/en/master/transport.html#caching) in an environment where sqlite wasn't bundled with your Python installation.

**Closed by msaniscalchi** 2022-12-15 02:43 UTC
