### ISSUE TITLE
googleads/dfp.py", line 328, in SetHeaders; 'Http' object has no attribute 'CreateHttpHeader'

### ISSUE THREAD

**Issue by gellel** [googleads/googleads-python-lib#151] opened 2016-09-13 01:01 UTC
Hello there. 

I am working with the DFP API attempting to create a basic connection using the server to server flow. I have noticed that a lot of the OAuth2 class package has changed since the set up of this project and I am experiencing this issue when attempting to use the basic `dfp.GetService('NetworkService').getAllNetworks()`. According to the output from the python interpreter there is an issue in the base library for `googleads`. 

The error is as follows:

    Traceback (most recent call last):
    File "dfp_test.py", line 33, in <module>
    print dfp_client.GetService('NetworkService').getAllNetworks()
    
    File "/Library/Python/2.7/site-packages/googleads/common.py", line 615, in MakeSoapRequest
    self._header_handler.SetHeaders(self.suds_client)
    
    File "/Library/Python/2.7/site-packages/googleads/dfp.py", line 328, in SetHeaders
    headers=self._dfp_client.oauth2_client.CreateHttpHeader())
    AttributeError: 'Http' object has no attribute 'CreateHttpHeader'

Is there an issue with the `googleads` client library using an older version of the OAuth2 library or is there a different issue at play here?

**Comment by msaniscalchi** [comment] 2016-09-13 14:41
Hello,

Thanks for the report! There have been a lot of changes in the latest version of oauth2client, but it doesn't seem like that is directly related to this issue. It sounds like you're using the Service Account flow?

The main issue I'm seeing here is that your DfpClient's GoogleOAuth2Client instance lacks the CreateHttpHeader method. There are a few possibilities that come to mind, but I think the most likely is that you're manually initializing the DfpClient and set the oauth2client field to something other than a GoogleOAuth2Client subclass.

**Comment by gellel** [comment] 2016-09-14 00:48
Hi @msaniscalchi ! Thank you so much for taking the time to look at my question. My apologies off the bat for not including my implementation flow. Yes, you guessed correctly; I am trying to set up a connection using server to server with a service account. 

I just tested that method of using the `GoogleOAuth2Client` subclass, and I received the an error around `oauth2client.client.SignedJwtAssertionCredentials` class method. From my previous tests, this error arises from the shuffling of the OAuth2 class and its depreciation or movement of certain classes. In this case `SignedJwtAssertionCredentials` has been moved to the newer `ServiceAccountCredentials` inside of `oauth2client.service_account`. 

When I try and use the new method, I receive the same issue as listed about the `CreateHttpHeader` unable to set because of a missing attribute in `Http`.

For further clarity, here is a simplified example of what I'm doing exactly. 



    from oauth2client.service_account import ServiceAccountCredentials
    from googleads import dfp

    import httplib2

    API_VER = 'v201608'
    APP_NAME = 'EXAMPLE'
    
    CLIENT_EMAIL = '[consolename]@[consoleproject].iam.gserviceaccount.com'
    PRIVATE_KEY = 'notasecret'
    SCOPES = ['https://www.googleapis.com/auth/dfp']
    P12_KEYS = 'PATH/TO/P12/FILE'
    NETWORK = 'https://www.google.com/dfp/[MYIDHERE]#delivery'

    credentials = ServiceAccountCredentials.from_p12_keyfile(CLIENT_EMAIL, P12_KEYS, SCOPES)
    http_auth = credentials.authorize(httplib2.Http())


    dfp_client = dfp.DfpClient(http_auth, APP_NAME, NETWORK)

    print dfp_client.GetService('NetworkService').getAllNetworks() ## this is where the error occurs

**Comment by msaniscalchi** [comment] 2016-09-14 16:16
Hello,

Unfortunately, this is a duplicate of Issue #110 after all. The gist of it is that our library [only supports oauth2client versions between 1.5.2 and 2.0.0](https://github.com/googleads/googleads-python-lib/blob/master/setup.py#L27) at this time. It's not ideal by any means, but there are factors preventing us from updating this library to use the latest version.

The good news is that I have already written the fix and it is undergoing review on our end currently. The less-good news is that it is a substantially larger change than one might expect, so clearing that review will still take a while.

Regards,
Mark

**Closed by msaniscalchi** 2016-09-14 16:16 UTC
