### ISSUE TITLE
AdWordsReportError is missing information from _ExtractRequestSummaryFields

### ISSUE THREAD

**Issue by drorbar** [googleads/googleads-python-lib#219] opened 2017-08-24 11:25 UTC
Hi,

I have a program that receives a report definition from the user and runs it on Adwords.
I've encountered a situation where the report failed and the exception is missing a good explanation for the failure, although this data exists in the headers of the response.

Example of the report: `{"selector":{"fields":["AccountCurrencyCode"]},"reportType":"GEO_PERFORMANCE_REPORT","includeZeroImpressions":"false"}`

I'm running the `report_downloader.DownloadReportAsString` and getting the following error:
 `AdWordsReportError('AdWords report download failed with HTTP status code: 400',)`.

In the log I see the following line: 
`googleads.adwords.report_downloader: Request Summary: {'clientCustomerId': 'xxx', 'includeZeroImpressions': 'false', 'server': 'adwords.google.com', 'skipColumnHeader': 'True', 'skipReportHeader': 'True', 'skipReportSummary': 'True', 'isError': True, 'errorMessage': '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><reportDownloadError><ApiError><type>SelectorError.MISSING_FIELDS</type><trigger>Must choose at least 1 field from the group [CountryCriteriaId]</trigger><fieldPath></fieldPath></ApiError></reportDownloadError>'}`

So I know we have more data about the error.
After digging in the code I found that the error is on the function: `_DownloadReportAsStream` on the line: `response = self.url_opener.open(request)`.
The logger writes the exception from the function `_ExtractRequestSummaryFields` but the exception is using the function `_ExtractError`.

Is there a way to add this kind of information to the `AdWordsReportError`?

**Comment by msaniscalchi** [comment] 2017-09-07 16:24
Actually, it's expected that the Exception should include the errorMessage as well. I can confirm that is not the case though; it seems this is a bug that was introduced with the enhanced logging.

Essentially, what is happening is that the same error's content is being read by both `_ExtractRequestSummaryFields` and `_ExtractError`. Since `_ExtractRequestSummaryFields` is done first, it has the correct content. On the other hand, `_ExtractError` is second, and consequently returns an empty string when reading the error's content.

Getting back to your question, yes, we can add this to the AdWordsReportError by resolving this bug. A temporary work-around may be to disable your logs if you really want this information in the Exception, but then you would have no logs... 

Regards,
Mark

**Closed** 2017-09-22 19:25 UTC
