### ISSUE TITLE
failed to install pypi packages. googleads has requirement pyyaml <6.0, >=5.1, but you have pyyaml 6.0

### ISSUE THREAD

**Issue by hnajari** [googleads/googleads-python-lib#510] opened 2022-10-13 15:12 UTC
**Describe the bug:**
Hi,
I got this error 

failed to install pypi packages. googleads has requirement pyyaml <6.0, >=5.1, but you have pyyaml 6.0

**Steps to Reproduce:**
I am using googleads with apache airflow package.
I am trying to upgrade airflow package from 2.2.5 to 2.3.3 version but i got this error 

`failed to install pypi packages. googleads has requirement pyyaml <6.0, >=5.1, but you have pyyaml 6.0`

**Expected behavior:**

**Client library version and API version:**
Client library version:
Google Ads API version: 33.0.0

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

**Comment by sahilkukreja** [comment] 2022-10-16 12:35
@hnajari  I am also facing the same issues i have raised the PR to fix the dependency issues

**Comment by hnajari** [comment] 2022-10-16 14:13
Thank you @sahilkukreja

**Comment by msaniscalchi** [comment] 2022-10-17 14:56
Thanks for the report! I'll investigate this along with the relevant PR shortly.

**Comment by msaniscalchi** [comment] 2022-10-17 15:58
I can't reproduce the exact issue on my end–if apache-airflow is installed first, attempting to install googleads afterwards causes the PyYaml installation to be downgraded. This is still workable because the PyYaml dependency for apache-airflow is defined as `PyYAML<7,>=5.1`. Installing in the opposite order also works as intended because PyYaml 5.4.1 is within the range of versions supported by apache-airflow. I'm not certain why your installation fails in comparison.

Of course, it makes sense to upgrade to 6.0 now that it is available. Given that this is a major version bump for the dependency, I want to run this through some test cases and verify that we won't introduce new breakages before adopting it.

**Comment by msaniscalchi** [comment] 2022-10-17 19:07
Relevant PR has been merged.

**Comment by sahilkukreja** [comment] 2022-10-18 06:31
@msaniscalchi  Thanks for merging the PR , by when can we expect PyPI Release ?
FYI. Steps to reproduce the issue  
upgrade composer environment to **2.0.28**  -   Airflow Version **2.3.3**
and Then try to install googleads 
[Composer-versions](https://cloud.google.com/composer/docs/concepts/versioning/composer-versions#images) if you check for  Version **composer-2.0.28-airflow-2.3.3** in PyPI packages for Python 3 we have `PyYAML==6.0` and we cant downgrade pyYAML as its used in other packages

**Comment by msaniscalchi** [comment] 2022-10-18 15:02
> Thanks for merging the PR , by when can we expect PyPI Release ?

It is dependent on a separate internal review that is ongoing. Given that it is not a complex change, I don't anticipate this should take long. It could happen as early as today, but could take up to a few days if our reviewer can't prioritize it in the short term.

**Closed** 2022-10-18 20:54 UTC

**Comment by sahilkukreja** [comment] 2022-10-18 21:02
@msaniscalchi Thanks for closing the issues and for quick response
