### ISSUE TITLE
estimate_keyword_traffic.py example throws error regarding suds

### ISSUE THREAD

**Issue by creepystranger** [googleads/googleads-python-lib#129] opened 2016-06-26 23:36 UTC
I am running the example script and its running fine and showing result ,but along the way it throws a bunch of error . 
**ERROR:suds.resolver:(Money) not-found
ERROR:suds.resolver:path: "Money", not-found
ERROR:suds.resolver:(Keyword) not-found
ERROR:suds.resolver:path: "Keyword", not-found
ERROR:suds.resolver:(Keyword) not-found
ERROR:suds.resolver:path: "Keyword", not-found
ERROR:suds.resolver:(Keyword) not-found
ERROR:suds.resolver:path: "Keyword", not-found
ERROR:suds.resolver:(Keyword) not-found
ERROR:suds.resolver:path: "Keyword", not-found
ERROR:suds.resolver:(Location) not-found
ERROR:suds.resolver:path: "Location", not-found
ERROR:suds.resolver:(Language) not-found
ERROR:suds.resolver:path: "Language", not-found**

could someone enlighten on how to fix these errors or this are something that I can ignore ,
I am using a test account at the moment .

**Comment by junna-zhou** [comment] 2016-09-27 09:07
the same problem, have you solve it ?

**Comment by parander** [comment] 2016-10-03 03:36
Duplicate of #35 #41 

I think you can ignore the error because the function seems to work as expected even though it prints all these errors. But your logs will of course get cluttered so the best would be if the error was "fixed" (i.e. removed if it's not really an error)

**Comment by msaniscalchi** [comment] 2016-10-03 15:26
I'm surprised that this has come up again. As mentioned in the previous comment, this is a duplicate of a re-opened issue, so I'll be closing this.

Even when it occurred last time, it was more of a cosmetic error logged by suds; the API call would otherwise work as intended. Until I get some time to look into this, it might make sense to temporarily disable the suds.resolver logger if this is flooding your logs.

**Closed by msaniscalchi** 2016-10-03 15:26 UTC

**Comment by junna-zhou** [comment] 2016-10-03 23:55
ok, i see.
thanks for your answers.
the API works fine, so I will disable the logger for suds.resolver.
