### ISSUE TITLE
Please Help: Python 3.6: TypeError, UTF-8 encoding WARNING in get_campagins.py

### ISSUE THREAD

**Issue by patrickbutler** [googleads/googleads-python-lib#257] opened 2018-03-12 14:16 UTC
Hi there,

I am running Python 3.6.

After setting up my googleads.yaml file, I am trying to run the get_campaigns.py script from the python client library and keep getting the following error (below).

It looks like I’m receiving a UTF-8 encoding warning and a TypeError. How would you recommend I resolve this issue?

WARNING:googleads.common:Your default encoding, cp1252, is not UTF-8. Please run this script with UTF-8 encoding to avoid errors.
DEBUG:suds.transport.http:opening (https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl)
INFO:oauth2client.client:Refreshing access_token
INFO:googleads.common:Request summary - {'methodName': get, 'clientCustomerId': 480-877-1368}
Traceback (most recent call last):
  File "get_campaigns.py", line 73, in <module>
    main(adwords_client)
  File "get_campaigns.py", line 56, in main
    page = campaign_service.get(selector)
  File "C:\Users\PButler\AppData\Local\Continuum\Anaconda3\lib\site-packages\googleads\common.py", line 791, in MakeSoapRequest
    self._packer) for arg in args])
  File "C:\Users\PButler\AppData\Local\Continuum\Anaconda3\lib\site-packages\suds\client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "C:\Users\PButler\AppData\Local\Continuum\Anaconda3\lib\site-packages\suds\client.py", line 581, in invoke
    result = self.send(soapenv)
  File "C:\Users\PButler\AppData\Local\Continuum\Anaconda3\lib\site-packages\suds\client.py", line 613, in send
    reply = self.options.transport.send(request)
  File "C:\Users\PButler\AppData\Local\Continuum\Anaconda3\lib\site-packages\googleads\util.py", line 121, in PatchedHttpTransportSend
    suds.transport.http.log.debug('sending:\n%s', request)
  File "C:\Users\PButler\AppData\Local\Continuum\Anaconda3\lib\logging\__init__.py", line 1294, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\Users\PButler\AppData\Local\Continuum\Anaconda3\lib\logging\__init__.py", line 1442, in _log
    self.handle(record)
  File "C:\Users\PButler\AppData\Local\Continuum\Anaconda3\lib\logging\__init__.py", line 1451, in handle
    if (not self.disabled) and self.filter(record):
  File "C:\Users\PButler\AppData\Local\Continuum\Anaconda3\lib\logging\__init__.py", line 718, in filter
    result = f.filter(record)
  File "C:\Users\PButler\AppData\Local\Continuum\Anaconda3\lib\site-packages\googleads\util.py", line 302, in filter
    self._REDACTED, msg)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by msaniscalchi** [comment] 2018-03-12 14:44
Hello Patrick,

Thanks for the report! This is a duplicate of issue #254. I'll shortly be investigating this and intend to have a fix in time for the next Adwords sunset release. As stated in the previously reported issue, there are a few work-arounds that can hold you over until then.

The issue appears to be isolated to our log filters. We enable these by default to exclude sensitive data from logs, so you can bypass this issue by either disabling logs entirely, or specifically [disabling our filters](https://github.com/googleads/googleads-python-lib#how-do-i-disable-log-filters).

I'll close this issue now, if you have additional concerns on this topic, please raise it in the original report.

Regards,
Mark

**Closed by msaniscalchi** 2018-03-12 14:44 UTC
Labels: P2, bug, duplicate
