### ISSUE TITLE
Unable to run the basic App Engine (Python) demo for Adwords API

### ISSUE THREAD

**Issue by GiladIMC** [googleads/googleads-python-lib#273] opened 2018-04-12 15:19 UTC
I have cloned and deployed the Python App Engine Demo for the AdWords API (from here)
After going through the tutorial multiple time to understand how to retrieve the refresh token I get the following error from the online app:

Error: ('Connection broken: IncompleteRead(299 bytes read)', IncompleteRead(299 bytes read))

I don't think it has something to do with the credentials I have provided (otherwise I would expect a more verbose error)

What am I missing?
I have a feeling it has to do with the App Engine Environment 

The application was deployed to the following link (not the flex environment):
https://adwordsimos.appspot.com

Any help would be appreciated 

Thanks

Gilad

**Comment by msaniscalchi** [comment] 2018-04-12 15:26
Hello Gilad,

Thanks for the report! Troubleshooting App Engine is a bit beyond the scope of this issue tracker, but I'll try to reproduce and verify if there is an underlying library issue at play here.

Regards,
Mark

**Comment by GiladIMC** [comment] 2018-04-12 15:29
Thank you for the quick reply!
I got directed here from the [AdWords Google group thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/adwords-api/h4vDTzEsw_o/XbTU4WsTCQAJ)

Thanks for the help!

**Comment by msaniscalchi** [comment] 2018-04-12 16:57
I've been able to reproduce the issue. Aside from what you reported, it appears there's potentially other issues as well.  For example:

* The [README.md](https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/adwords_appengine_demo/README.md#step-by-step-guide-for-using-adwords-api-demo-on-app-engine) suggests that all dependencies can be installed; however, `lxml` actually needs to be manually added via changes to the [app.yaml](https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/adwords_appengine_demo/app.yaml#L16) file.
* The googleads version specified in [requirements.txt](https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/adwords_appengine_demo/requirements.txt#L1) is not up to date, but also not usable because it refers to a patch release that wasn't actually released on PyPI. It should be 11.0.1, to reflect the current version.

While I haven't confirmed the root cause yet, I can confirm that the example works on 10.1.0. It seems likely related to the changes introduced in 11.0.0.

**Comment by GiladIMC** [comment] 2018-04-12 17:10
I was able to solve these two issues (took me a while :) ) 
Would you recommend that I use 10.1.0 in the meantime so I could advance with my project?

**Comment by msaniscalchi** [comment] 2018-04-12 18:52
Additional issues discovered:

* The cause of the reported issue is a ChunkedEncodingError, that occurs because the requests library and App Engine don't work so well together by default. See the [work-around](https://toolbelt.readthedocs.io/en/latest/adapters.html#appengineadapter).
* By default, AdWordsClient will use Zeep. In `api_handler.py`, the `APIHandler.__init__` should specify a cache kwarg value of `ZeepServiceProxy.NO_CACHE`.

All of these issues are actually isolated to the example itself; no changes to the client in 11.0.0/1 will be necessary. You *can* work with this version, provided that you make the aforementioned changes. As mentioned earlier, we'll push these changes with the next release.

**Comment by msaniscalchi** [comment] 2018-05-17 15:17
This was fixed in the last release.

**Closed by msaniscalchi** 2018-05-17 15:17 UTC
Labels: P2, bug
