### ISSUE TITLE
Googleads value error when upgraded lib version

### ISSUE THREAD

**Issue by developerlicw** [googleads/googleads-python-lib#330] opened 2018-09-26 08:39 UTC
Hello,
Thanks very much for the great lib,  I am working with adwords api using it right now.
Recently, when I upgraded my lib's version, the following error occurs:
`googleads.errors.GoogleAdsValueError: Given yaml file, /home/developer/googleads.yaml, could not find some keys. Please replace the "dfp" key in the configuration YAML string with"ad_manager" to fix this issue.`
But actually, I haven't touched my yaml file at all, I'm not even using dfp.
Here are my version used:

**version after upgrade:** 
googleads==14.1.0

**version before upgrade**
googleads==12.2.0

And there seems to be others confused by this issue:
https://groups.google.com/forum/?hl=fy#!topic/adwords-api/aPmQZhRfMmo

According to google adwords api team, this should be an error on library side, so I wonder whether there is something I'm missing since library is 14.1.0 now.

Thanks for all your help in advance.

**Comment by msaniscalchi** [comment] 2018-09-26 13:38
Hello,

Thanks for the report! This looks like a duplicate of Issue #324. You just need to remove the dfp key from your old **googleads.yaml** file in order to resolve this. Check out the originally reported issue for more details.

Regards,
Mark

**Closed by msaniscalchi** 2018-09-26 13:38 UTC

**Comment by developerlicw** [comment] 2018-09-26 23:59
Hi msaniscalchi,
A lot thanks for your comment, it's quite useful for my work:)
Sorry for the duplication.
