### ISSUE TITLE
'HTTPSConnectionWithTimeout' object has no attribute 'proxy_info'

### ISSUE THREAD

**Issue by Lalit7Jain** [googleads/googleads-python-lib#264] opened 2018-03-25 17:57 UTC
I am trying to work on a very simple remarketing audience code through adwords. Below is the code to test

```
from googleads import adwords
import uuid

adwords_client = adwords.AdWordsClient.LoadFromStorage()

user_list_service = adwords_client.GetService(
    'AdwordsUserListService', version='v201710')

operations = [
    {
        'operator': 'ADD',
        'operand': {
            'xsi_type': 'BasicUserList',
            'name': 'Mars cruise customers #%s' % uuid.uuid4(),
            'description': 'A list of mars cruise customers in the last year',
            'membershipLifeSpan': '365',
            'conversionTypes': [
                {
                    'name': ('Mars cruise customers #%s'
                             % uuid.uuid4())
                }
            ],
            # Optional field.
            'status': 'OPEN',
        }
    }
]
user_list_result = user_list_service.mutate(operations)
```

I have all the package installed with the latest versions, but I am getting the following issue. Full traceback here:

`Traceback (most recent call last):
  File "/Users/ljain/PycharmProjects/AdwordAudience/test.py", line 33, in <module>
    user_list_result = user_list_service.mutate(operations)
  File "/Users/ljain/PycharmProjects/AdwordAudience/venv1/lib/python3.6/site-packages/googleads/common.py", line 786, in MakeSoapRequest
    self._header_handler.SetHeaders(self.suds_client)
  File "/Users/ljain/PycharmProjects/AdwordAudience/venv1/lib/python3.6/site-packages/googleads/adwords.py", line 566, in SetHeaders
    http_headers = self._adwords_client.oauth2_client.CreateHttpHeader()
  File "/Users/ljain/PycharmProjects/AdwordAudience/venv1/lib/python3.6/site-packages/googleads/oauth2.py", line 211, in CreateHttpHeader
    self.Refresh()
  File "/Users/ljain/PycharmProjects/AdwordAudience/venv1/lib/python3.6/site-packages/googleads/oauth2.py", line 226, in Refresh
    self.proxy_config.disable_certificate_validation)))
  File "/Users/ljain/PycharmProjects/AdwordAudience/venv1/lib/python3.6/site-packages/oauth2client/client.py", line 545, in refresh
    self._refresh(http)
  File "/Users/ljain/PycharmProjects/AdwordAudience/venv1/lib/python3.6/site-packages/oauth2client/client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "/Users/ljain/PycharmProjects/AdwordAudience/venv1/lib/python3.6/site-packages/oauth2client/client.py", line 780, in _do_refresh_request
    body=body, headers=headers)
  File "/Users/ljain/PycharmProjects/AdwordAudience/venv1/lib/python3.6/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/Users/ljain/PycharmProjects/AdwordAudience/venv1/lib/python3.6/site-packages/httplib2/__init__.py", line 1513, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/ljain/PycharmProjects/AdwordAudience/venv1/lib/python3.6/site-packages/httplib2/__init__.py", line 1263, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/ljain/PycharmProjects/AdwordAudience/venv1/lib/python3.6/site-packages/httplib2/__init__.py", line 1186, in _conn_request
    conn.connect()
  File "/Users/ljain/PycharmProjects/AdwordAudience/venv1/lib/python3.6/site-packages/httplib2/__init__.py", line 982, in connect
    if self.proxy_info and self.proxy_info.isgood():
AttributeError: 'HTTPSConnectionWithTimeout' object has no attribute 'proxy_info'`

I am running this on a Virtual environment as well. Also, tokens are used by other user and I am using the same token to work here as well.

**Comment by msaniscalchi** [comment] 2018-03-26 13:55
Hello,

Thanks for the report! This is a duplicate of Issue #260, where httplib2 introduced a breaking change in a minor release. A temporary work-around would be to downgrade httplib2, although we'll be pushing a change later this week that removes it as a dependency.

I'll close this issue for now, please follow Issue #260 to track this.

Regards,
Mark

**Closed by msaniscalchi** 2018-03-26 13:55 UTC
