### ISSUE TITLE
AttributeError: 'str' object has no attribute 'CreateHttpHeader'

### ISSUE THREAD

**Issue by maran1989** [googleads/googleads-python-lib#253] opened 2018-03-01 21:05 UTC
in SetHeaders

http_headers = self._adwords_client.oauth2_client.CreateHttpHeader()

all credentials are in there and I keep getting this error

**Comment by msaniscalchi** [comment] 2018-03-02 15:46
Hello,

Thanks for the report! I'm not able to replicate this issue, but the error seems to be indicating that `oauth2_client` is a string. That should be a `googleads.oauth2.GoogleOAuth2Client` subclass, so if I had to guess, it sounds like the root cause of this issue is related to the instantiation of the AdWordsClient. If you're instantiating manually, I'd recommend you verify that you are passing arguments in the proper order.

If you can verify that your client is created correctly, I'll need some additional information. For example, a code snippet and details on your environment would be helpful.

Regards,
Mark

**Comment by maran1989** [comment] 2018-03-02 16:23
adwords_client = adwords.AdWordsClient(
            'my-dev-token', 
            'my-client-id',
            'my-user-agent', 
            client_customer_id= 'my-client-customer-id')

this is my code.

**Comment by maran1989** [comment] 2018-03-02 16:26
I am using LoadFromStorage(path) now but it would be great to customize the clients credentials.

**Comment by msaniscalchi** [comment] 2018-03-02 16:27
Right, that looks like the cause. Take a look at the [AdWordsClient initializer](https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L340).

**Comment by maran1989** [comment] 2018-03-02 16:40
Thanks! But can you give me a sample syntax to initiate correctly. It would be a big help!

**Comment by msaniscalchi** [comment] 2018-03-02 18:06
Sure, the [create_adwords_client_with_refresh_token](https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/authentication/create_adwords_client_with_refresh_token.py) example should cover this.

**Comment by msaniscalchi** [comment] 2018-03-16 16:32
It looks like this has been resolved, so I'll close this. Feel free to reopen if I'm mistaken.

**Closed by msaniscalchi** 2018-03-16 16:32 UTC
