### ISSUE TITLE
getCreativesByStatement returns empty 'results' field

### ISSUE THREAD

**Issue by rdailey-808** [googleads/googleads-python-lib#287] opened 2018-05-31 15:38 UTC
It looks like getCreativesByStatement now returns an empty results field instead of removing the results field from the response.  Example:
```
{
    'totalResultSetSize': 159,
    'startIndex': 500,
    'results': []
}
```

This results in an infinite loop if any code is based on the examples provided.  From the samples provided:
```
while True:
response = creative_service.getCreativesByStatement(statement.ToStatement())
if 'results' in response:
  for creative in response['results']:
    # Print out some information for each creative.
    print('Creative with ID "%d" and name "%s" was found.\n' %
          (creative['id'], creative['name']))
  statement.offset += statement.limit
else:
  break
```

Based on the latest changes, "if 'results' in response:" will always be true.  All samples would need to be updated with the following: 
`if response['results']:`

UPDATE:
I just verified the release notes for v201805 and it does not mention any changes to creative_service.

**Comment by grivescorbett** [comment] 2018-06-04 13:44
This looks like a duplicate of #284, it's definitely related to switching over to Zeep. Working on a fix now.

**Closed by grivescorbett** 2018-06-04 13:44 UTC
