### ISSUE TITLE
GZIPPED_CSV

### ISSUE THREAD

**Issue by Olmer1st** [googleads/googleads-python-lib#175] opened 2017-01-15 16:36 UTC
Hi,

Updated today to newest version of client library.
Started to use enable_compression and trying to download GZIPPED_CSV using DownloadReport method.
Everything work much better. But i can't extract the data... is this gz file?
Should i use download stream instead DownloadReport?

**Comment by Olmer1st** [comment] 2017-01-16 08:13
I think the file created after download corrupted...

**Comment by Olmer1st** [comment] 2017-01-16 12:39
Update: gunzip and Archive Manager (ubuntu) can't extract file, but the code below work well:
` try:
                            with gzip.open(report_file_path, 'rb') as in_file:
                                extracted_content = in_file.read()
                        except Exception as err:
                            pass

                        # Now store the uncompressed data
                        path_to_store = "{0}.{1}".format(report_file_path[:-3], extracted_extension) # remove the '.gz' from the filename and change extension
                        # store uncompressed file data from 'extracted_content' variable
                        with open(path_to_store, 'w') as extracted_file:
                            extracted_file.write(extracted_content)`

**Comment by msaniscalchi** [comment] 2017-01-17 15:55
Hello,

Thanks for the report! It's specifically gzipped reports that are affected? That's definitely interesting. I have a few ideas regarding possible causes. I'll reproduce and see if I can confirm.

Regards,
Mark

**Comment by msaniscalchi** [comment] 2017-01-17 23:04
I can't reproduce the issue, downloading a `GZIPPED_CSV` report with `compression_enabled` set to `True` works as expected on my end. Digging a little deeper though, I don't think the issue you're reporting was introduced in 5.0.0, because usage of the new `enable_compression` argument doesn't impact the ReportDownloader--it is only applied to API requests.

I'd appreciate if you could provide some details about your environment.  Also, if you can reliably reproduce the issue, I'd like to take a look at some code.

**Comment by Olmer1st** [comment] 2017-01-18 16:07
Hi,

Thanks for replay.
enable_compression impact ReportDownloader  too, because without this parameter download time preserve the same like to download CSV

environment:
Ubuntu 16.04
python 2.7
flask

The problem exist when I try to extract file created from download using gunzip or other tools in ubuntu
Extract in python work well.

**Comment by msaniscalchi** [comment] 2017-01-18 16:45
I've verified that `accept-encoding: gzip` isn't included in the `ReportDownloader` headers when `enable_compression` is set to `True`. I'm pretty confident that the usage of `enable_compression` introduced in 5.0.0 isn't directly related to the issue you're reporting.

I've modified an existing sample to download the GZIPPED report to a file, and then successfully used gunzip to extract the report. The only notable difference is that I'm running from the command-line rather than a Flask web app. For purposes of isolating the issue, could you run the following script and confirm whether or not you're able to extract the report? Does this change for you depending on the setting of `enable_compression`?

```
import sys
from googleads import adwords


def main(client):
  report_downloader = client.GetReportDownloader(version='v201609')

  # Create report definition.
  report = {
      'reportName': 'Last 7 days CRITERIA_PERFORMANCE_REPORT',
      'dateRangeType': 'LAST_7_DAYS',
      'reportType': 'CRITERIA_PERFORMANCE_REPORT',
      'downloadFormat': 'GZIPPED_CSV',
      'selector': {
          'fields': ['CampaignId', 'AdGroupId', 'Id', 'CriteriaType',
                     'Criteria', 'FinalUrls', 'Impressions', 'Clicks', 'Cost']
      }
  }

  with open('criteria_performance_report.csv.gz', 'wb') as handler:
    report_downloader.DownloadReport(
        report, handler, skip_report_header=False, skip_column_header=False,
        skip_report_summary=False)


if __name__ == '__main__':
  adwords_client = adwords.AdWordsClient.LoadFromStorage()
  main(adwords_client)
```

**Comment by Olmer1st** [comment] 2017-01-19 09:25
Hi,
You are right. The problem was with extension : with csv.gz  export work with all tools.
And enable_compression not help in case of download.
And it's a problem - download big csv take the same time with GZIPPED_CSV and CSV. But when i do it with wget --header='accept-encoding: gzip' speed of download improved  x20 instead 60 second it take 3 sec. How to do the same with the library?

**Comment by msaniscalchi** [comment] 2017-01-19 17:03
Thanks for confirming, glad you got it working again.

I'll investigate the performance issue you're reporting for report downloads where accept-encoding is set. If the report definition indicates you want a GZIPPED_CSV, I wouldn't expect the time to differ regardless of whether the accept-encoding header was set.

At this time, there is no built-in functionality that would set "accept-encoding: gzip" or the ReportDownloader because the expectation was that the report definition would determine the format of the returned report. I can look into whether it makes sense for us to change this going forward.

**Comment by msaniscalchi** [comment] 2017-06-09 19:02
After looking into this, I do see that wget is generally slightly faster--sometimes it's about on par. The difference I'm seeing on my end is pretty easily explained by the fact that the ReportDownloader is constructing and encoding the SOAP body sent in the request. In contrast, there's no processing being done with the equivalent wget request because all of the fields were manually provided.

That said, your report sounds a bit more extreme. The most plausible idea that comes to mind is that you may be using some sort of proxy with the Python Client Library that may be impacting the download speed.

Given that I can't identify the specific issue on my end and there have been no further reports, I will close this issue for now.

**Closed by msaniscalchi** 2017-06-09 19:02 UTC
