### ISSUE TITLE
examples add_site_links dont work

### ISSUE THREAD

**Issue by maximprokopenko** [googleads/googleads-python-lib#68] opened 2015-08-03 09:26 UTC
I set CAMPAIGN_ID, but:
/examples/adwords/v201506/extensions/add_site_links.py
```
suds.WebFault: Server raised fault: 'Unmarshalling Error: cvc-complex-type.2.3: Element 'ns0:sitelinkFinalUrls' cannot have character [children], because the type's content type is element-only.
```

/examples/adwords/v201502/extensions/add_site_links.py
```
suds.WebFault: Server raised fault: '[EntityAccessDenied.WRITE_ACCESS_DENIED @ operations[0].operand.extensionSetting.extensions]
```

**Comment by msaniscalchi** [comment] 2015-08-11 19:20
Hello,

Thanks for the report! Could you provide some additional information, such as what version of Python / suds-jurko you are using? I can't reproduce the behavior you're describing with the latest versions.

**Comment by maximprokopenko** [comment] 2015-08-12 07:40
Python 2.7.6
suds-jurko
Version: 0.6

**Comment by maximprokopenko** [comment] 2015-08-12 08:49
I updated googleads-python-lib.
/examples/adwords/v201502/extensions/add_site_links.py
```
No handlers could be found for logger "suds.client"
Traceback (most recent call last):
  File "./extensions/add_site_links.py", line 128, in <module>
    main(adwords_client, CAMPAIGN_ID)
  File "./extensions/add_site_links.py", line 114, in main
    response = campaign_extension_setting_service.mutate([operation])
  File "/usr/local/lib/python2.7/dist-packages/googleads/common.py", line 297, in MakeSoapRequest
    for arg in args])
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 619, in send
    description=tostr(e), original_soapenv=original_soapenv)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 670, in process_reply
    raise WebFault(fault, replyroot)
suds.WebFault: Server raised fault: '[EntityAccessDenied.WRITE_ACCESS_DENIED @ operations[0].operand.extensionSetting.extensions[0].sitelinkUrl, EntityAccessDenied.WRITE_ACCESS_DENIED @ operations[0].operand.extensionSetting.extensions[1].sitelinkUrl, EntityAccessDenied.WRITE_ACCESS_DENIED @ operations[0].operand.extensionSetting.extensions[2].sitelinkUrl, EntityAccessDenied.WRITE_ACCESS_DENIED @ operations[0].operand.extensionSetting.extensions[3].sitelinkUrl]'
```

/examples/adwords/v201506/extensions/add_site_links.py

```
No handlers could be found for logger "suds.client"
Traceback (most recent call last):
  File "./v201506/extensions/add_site_links.py", line 128, in <module>
    main(adwords_client, CAMPAIGN_ID)
  File "./v201506/extensions/add_site_links.py", line 114, in main
    response = campaign_extension_setting_service.mutate([operation])
  File "/usr/local/lib/python2.7/dist-packages/googleads/common.py", line 297, in MakeSoapRequest
    for arg in args])
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 619, in send
    description=tostr(e), original_soapenv=original_soapenv)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 670, in process_reply
    raise WebFault(fault, replyroot)
suds.WebFault: Server raised fault: '[UrlError.DESTINATION_URL_DEPRECATED @ operations[0].operand.extensionSetting.extensions[0].sitelinkUrl, UrlError.DESTINATION_URL_DEPRECATED @ operations[0].operand.extensionSetting.extensions[1].sitelinkUrl, UrlError.DESTINATION_URL_DEPRECATED @ operations[0].operand.extensionSetting.extensions[2].sitelinkUrl, UrlError.DESTINATION_URL_DEPRECATED @ operations[0].operand.extensionSetting.extensions[3].sitelinkUrl]'
```

**Comment by jradcliff** [comment] 2015-08-31 20:40
[This discussion](https://groups.google.com/d/msg/adwords-api/iYhpm7Cp1kU/6qq3Y8m6CAAJ) on the AdWords API group contains more details.

The example should be setting `sitelinkFinalUrls` to an *array* of URLs instead of setting `sitelinkUrl`.

See the [equivalent Java example](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/java/adwords/axis/v201502/extensions/AddSiteLinks.java#L150) for details.

**Comment by jradcliff** [comment] 2015-09-01 13:50
Sorry -- since the type of `sitelinkFinalUrls` should be [UrlList](https://developers.google.com/adwords/api/docs/reference/v201506/CampaignExtensionSettingService.UrlList), the code should be:

     sitelink1 = {
         'xsi_type': 'SitelinkFeedItem',
         'sitelinkText': 'Store Hours',
         'sitelinkFinalUrls': {'urls': ['http://www.example.com/storehours']}
     }

**Comment by msaniscalchi** [comment] 2016-02-16 23:04
This was resolved in an earlier release.

**Closed by msaniscalchi** 2016-02-16 23:04 UTC
