### ISSUE TITLE
Library picking incorrect encoder?

### ISSUE THREAD

**Issue by odnapetlya** [googleads/googleads-python-lib#55] opened 2015-05-06 15:48 UTC
I have the code:

    report_downloader = client.GetReportDownloader(version='v201409')
    report_query = ('SELECT Impressions,QualityScore,KeywordText ' +
                    'FROM KEYWORDS_PERFORMANCE_REPORT ' +
                    'WHERE Impressions > 0 ' +
                    'DURING YESTERDAY ')
    r = report_downloader.DownloadReportAsStringWithAwql(report_query, 'CSV').splitlines()

And I get the exception:

    Traceback (most recent call last):
      File "qs_tracking.py", line 100, in <module>
        qs_report(list_of_customer_ids, tracking_config)
      File "qs_tracking.py", line 68, in qs_report
        r = qs_report_one_acc(client)
      File "qs_tracking.py", line 34, in qs_report_one_acc
        r = report_downloader.DownloadReportAsStringWithAwql(report_query, 'CSV').splitlines()
      File "/usr/local/lib/python2.7/dist-packages/googleads/adwords.py", line 635, in DownloadReportAsStringWithAwql
        return response.read().decode()
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 55408: ordinal not in range(128)

This only happens in one of my accounts. In the others this code runs fine.

**Comment by msaniscalchi** [comment] 2015-05-06 20:22
Thanks for the report. It looks like a regression was introduced where unicode wasn't decoded properly for reports. We'll push out a fix in the next release.

**Comment by odnapetlya** [comment] 2015-05-11 14:31
Hi

Just replacing with

    return response.read().decode('utf-8')

works.

**Comment by msaniscalchi** [comment] 2015-05-11 20:05
Hello,

Right, that should work if you want to apply a local change for a short-term fix. This fix is bundled with the next release; I'll close this issue once it has been made available.

**Closed** 2015-05-22 19:02 UTC

**Comment by jegesh** [comment] 2015-11-11 11:13
I seem to be getting a very similar error, just having trouble understanding what changes should be made.  Here's the stacktrace:

`Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
  File "/Users/nerdeez/Development/workspace/moonshot/moonshot-backend/venv/lib/python2.7/site-packages/suds/__init__.py", line 168, in <lambda>
    __str__ = lambda x: unicode(x).encode('utf-8')
  File "/Users/nerdeez/Development/workspace/moonshot/moonshot-backend/venv/lib/python2.7/site-packages/suds/transport/__init__.py", line 96, in __unicode__
    %s""" % (self.code, self.headers, self.message)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4612971: ordinal not in range(128)`

**Comment by msaniscalchi** [comment] 2015-11-11 15:58
Hello,

This actually doesn't appear to be related. It looks like the same issue detailed in [issue #32 in the suds-jurko library](https://bitbucket.org/jurko/suds/issues/32/logdebug-unicode-encoding-problem-in). A pull request was submitted there that has a fix; otherwise, it was reported that setting the suds.transport to the INFO logging level at least allows you to avoid the issue.

I suggest adding your voice to that bug and watching it to draw more attention to it.

**Comment by jegesh** [comment] 2015-12-13 19:21
Thanks for the redirect!
