### ISSUE TITLE
AppEnginePlatformWarning

### ISSUE THREAD

**Issue by juceberipe** [googleads/googleads-python-lib#303] opened 2018-07-09 11:52 UTC
My project uses these python libraries:

requests==2.19.1
requests-toolbelt==0.8.0
and calls this at the main.py

requests_toolbelt.adapters.appengine.monkeypatch()
App engine is logging Error message inside google cloud logs when using the requests library:

AppEnginePlatformWarning: urllib3 is using URLFetch on Google App Engine sandbox instead of sockets. To use sockets directly instead of URLFetch see https://urllib3.readthedocs.io/en/latest/reference/urllib3.contrib.html.

AppEnginePlatformWarning: URLFetch does not support granular timeout settings, reverting to total or default URLFetch timeout.

**Comment by msaniscalchi** [comment] 2018-07-12 20:29
Hello,

Thanks for the report! I've run this application myself and have not been able to reproduce the error message you're reporting--is there a particular page in the demo where you see this as an error message in the App Engine logs? My logs report no app / server errors. Although, it seems possible that this may be because you're running from a sandbox and my app is deployed.

That said, even if it were reproducible, I don't think this is an issue we could resolve here because it seems to be related to the [requests-toolbelt](https://github.com/requests/toolbelt) library.

Regards,
Mark

**Comment by msaniscalchi** [comment] 2018-07-18 19:03
I'm going to close this issue given that it has not been reproduced, doesn't seem actionable, and hasn't seen follow-up for a week.

Of course, feel free to reopen.

**Closed by msaniscalchi** 2018-07-18 19:03 UTC
