### ISSUE TITLE
GoogleAds doesn't return data and get stuck on a Keywords performance report

### ISSUE THREAD

**Issue by Alonreznik** [googleads/googleads-python-lib#400] opened 2019-05-09 17:05 UTC
Hi There.
Recently, we're encountering a bug in our Google Ads python library, when trying to receive data of Keywords Performace response. The Google library just waiting over than 50 minutes to get data back and stuck the process.

Our report is:

```
{'reportName': 'KEYWORDS_PERFORMANCE_REPORT', 
 'selector': {
   'fields': ['Account', 'Currency', 'Activeviewviewableimpressions', 'Adgroupid', 'Adgroup', 'Adgroupstate', 'Network', 'Campaign', 'Campaignid', 'Clicks', 'Keyword', 'Keywordid', 'Impressions', 'Trackingtemplate', 'Day', 'Device', 'Customerid', 'Views', 'View-Throughconv.', 'Clientname', 'Conversions', 'Totalconv.Value', 'Cost', 'Bidstrategyid', 'Verticalid'], 
  'dateRange': {'max': '20190509', 'min': '20190507'}
}, 
   'reportType': 'KEYWORDS_PERFORMANCE_REPORT', 
    'dateRangeType': 'CUSTOM_DATE', '
downloadFormat': 'TSV'} 
```

Is there any way to run the reports using pagination, or see what can we do in these cases, when a report runs a very long time? 
How can we make these run to be quicker?

Thanks

Alon

**Comment by Alonreznik** [comment] 2019-05-22 21:57
Hi Guys.
Any remark?
Thanks

**Comment by BenRKarl** [comment] 2019-07-09 21:11
Hi @Alonreznik apologies for the delay. Is there an indication that this issue is related to the Python library specifically and not the API? It's possible that the delay may be coming from the API itself and not the client library, perhaps due to an expensive query. If that's the case it would be better to request support via the [support forum](https://groups.google.com/forum/#!forum/adwords-api).

I'm going to close this for now, but please re-open the issue if you believe the problem is related to this library and not the API.

**Closed by BenRKarl** 2019-07-09 21:11 UTC
