### ISSUE TITLE
Data Issue in AdGroup Performance Report for AdGroupMobileBidModifier 

### ISSUE THREAD

**Issue by suvodhoy** [googleads/googleads-python-lib#104] opened 2016-03-04 13:05 UTC
Hi @msaniscalchi
I see an inconsistency in the data in Ad Group Performance Report. We have four variations of setting mobile bid modifier in the adwords interface. For each of these I have mentioned the value  which comes in the report under the column **mobileBidAdj**

1. 0% :  1.0
2.  20% (this is an example value can be in -90% to 300%)  :  1.2
3. leave blank (**--**)  :  0.0
4. -100%  :  0.0

As you will notice the value is same for the 3rd and 4th option which makes it very difficult to distinguish. Is this expected or am I missing something?

**Comment by msaniscalchi** [comment] 2016-03-04 15:57
Hello,

This appears more related to the API itself than the behavior of the client libraries, in which case the [AdWords Support Forums](https://groups.google.com/forum/#!forum/adwords-api) would probably be a better location to report the issue.

While it does seem that options 3 & 4 should result in the same value, they do at least **effectively** do the same thing--the [AdGroupBidModifier documentation](https://developers.google.com/adwords/api/docs/reference/v201601/AdGroupBidModifierService.AdGroupBidModifier#bidmodifier) for the `bidModifier` field gives a pretty good description of what the expected behavior is.

A bid modifier of 0.0 suggests that you are opting out of mobile. I think you are seeing an inconsistent way in which this is being represented--it could be left blank to indicate that you're not bidding on mobile, but a value of -100% also indicates that you're not bidding on mobile inventory. I'll talk to the AdWords team about this and see if this difference is intended and/or meaningful in any way.

**Comment by salilpa** [comment] 2016-03-04 19:04
Hi

I will put it up in the Adwords Support Forum also.

Just to add one point. As per our knowledge, if you are leaving the modifier blank ,ie, --, it means you are using the same bid for mobile. So 0% and -- both mean the same and should ideally return 1.0 for both if not 1.0 and -- respectively. The functional difference between 0% and -- comes when you have a campaign level bid modifier and you want to override that in the ad group.

**Comment by msaniscalchi** [comment] 2016-03-04 20:56
I've contacted the AdWords team on this; they're looking into it and are aware of your [thread](https://groups.google.com/forum/#!topic/adwords-api/GCC8hdcXClo) on the support forum.

Since this isn't directly related to the Python library, I will now close this issue.

**Closed by msaniscalchi** 2016-03-04 20:56 UTC
