### ISSUE TITLE
Proxy configuration not applied to oauth2 client

### ISSUE THREAD

**Issue by liusand** [googleads/googleads-python-lib#218] opened 2017-08-16 16:20 UTC
I'm trying to figure out how to configure proxy for Python client 6.1.0, for which the API version I believe is v201708. I passed in proxy info like the following when creating the service client.

        http_proxy=googleads.common.ProxyConfig.Proxy('proxy host w/o http://', 8080)

        https_proxy=googleads.common.ProxyConfig.Proxy('proxy host w/o https://', 8080)

        proxy_config = googleads.common.ProxyConfig(http_proxy=http_proxy, https_proxy=https_proxy)

        client = adwords.AdWordsClient(DEVELOPER_TOKEN, OAUTH_CLIENT, USER_AGENT, client_customer_id=account_id, proxy_config=proxy_config)

However, when accessing the API it looks like oauth2 client still tries to access google servers like dfw25s27-in-f13.1e100.net.https directly. Below is the stack trace concerning the Python client.

  File "/usr/local/lib/python2.7/site-packages/googleads/common.py", line 743, in MakeSoapRequest

    self._header_handler.SetHeaders(self.suds_client)

  File "/usr/local/lib/python2.7/site-packages/googleads/adwords.py", line 554, in SetHeaders

    http_headers = self._adwords_client.oauth2_client.CreateHttpHeader()

  File "/usr/local/lib/python2.7/site-packages/googleads/oauth2.py", line 211, in CreateHttpHeader

    self.Refresh()

  File "/usr/local/lib/python2.7/site-packages/googleads/oauth2.py", line 226, in Refresh

    self.proxy_config.disable_certificate_validation)))

  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 545, in refresh

    self._refresh(http)

  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 749, in _refresh

    self._do_refresh_request(http)

  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 780, in _do_refresh_request

    body=body, headers=headers)

  File "/usr/local/lib/python2.7/site-packages/oauth2client/transport.py", line 282, in request

    connection_type=connection_type)

  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1659, in request

    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)

  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1399, in _request

    (response, content) = self._conn_request(conn, request_uri, method, body, headers)

  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1355, in _conn_request

    response = conn.getresponse()

  File "/usr/local/lib/python2.7/httplib.py", line 1123, in getresponse

    raise ResponseNotReady()

httplib.ResponseNotReady

Any idea whether this can be fixed on our side or is a bug with the Python client?

Thanks,
Sha Liu

**Comment by msaniscalchi** [comment] 2017-08-22 07:09
Hello,

> However, when accessing the API it looks like oauth2 client still tries to access google servers like dfw25s27-in-f13.1e100.net.https directly.

If this is the case, it is likely more of an issue with the oauth2client dependency, given that we provide an Http instance initialized with the provided proxy configuration (as a ProxyInfo instance) to the OAuth2Credentials instance. I'll investigate this.

> File "/usr/local/lib/python2.7/httplib.py", line 1123, in getresponse
raise ResponseNotReady()
Any idea whether this can be fixed on our side or is a bug with the Python client?

So it sounds like you aren't able to actually make calls then? At the moment, I can say that it isn't something I have reproduced. We use a proxy for testing purposes, and we are able to successfully make API calls while using the proxy.

Regards,
Mark

**Comment by liusand** [comment] 2017-08-22 21:02
Hi Mark,

Thanks for checking this.

You're correct we're not able to make API calls. We're behind a firewall without direct Internet access. So if any component tries to connect to Internet directly the connection will fail. From what we've seen using tcpdump, the packets were sent directly to somewhere under 1e100.net:443, while our proxy uses port 8080.

Regards,
Sha

**Comment by msaniscalchi** [comment] 2017-12-22 23:05
I've not been able to reproduce this behavior, but just had a forehead-slapping moment when re-examining the code you sent over earlier:

```
http_proxy=googleads.common.ProxyConfig.Proxy('proxy host w/o http://', 8080)
https_proxy=googleads.common.ProxyConfig.Proxy('proxy host w/o https://', 8080)
proxy_config = googleads.common.ProxyConfig(http_proxy=http_proxy, https_proxy=https_proxy)
client = adwords.AdWordsClient(DEVELOPER_TOKEN, OAUTH_CLIENT, USER_AGENT, client_customer_id=account_id, proxy_config=proxy_config)
```
It's actually not enough to provide the ProxyConfig instance to the AdWordsClient. In order for it to be applied to whichever `GoogleOAuth2Client` subclass you're using for OAuth 2.0, you need to instantiate it with a `proxy_config` keyword argument. It looks like you passed the ProxyConfig over to the AdWordsClient, but forgot to pass it to the GoogleRefreshTokenClient(?) you were using.

Regards,
Mark

**Closed by msaniscalchi** 2017-12-22 23:05 UTC
