### ISSUE TITLE
urllib.error.URLError: <urlopen error [WinError 10053] 

### ISSUE THREAD

**Issue by jaehancrate** [googleads/googleads-python-lib#241] opened 2017-12-01 17:51 UTC
Wondering if someone here can help me. This is a strange issue as I was able to submit CRM based user lists for the Customer Match program. But I am not getting this error:
I have no issues getting the user list created, but when I perform a mutate operation on the existing dataset it returns this error:

urllib.error.URLError: <urlopen error [WinError 10053] An established connection was aborted by the software in your host machine>
```

adwords_client = adwords.AdWordsClient.LoadFromStorage('googleads.yaml')
user_list_service = adwords_client.GetService('AdwordsUserListService', 'v201710')

# print("Creating Audience Now")
# user_list = {
#       'xsi_type': 'CrmBasedUserList',
#       'name': 'Customer Match Home Address Control Group: {}'.format(num_control),
#       'description': 'Customer Match by Home Address Control Group',
#       'membershipLifeSpan': 180
#   }

# # Create an operation to add the user list.
# operations = [{
#   'operator': 'ADD',
#   'operand': user_list
# }]

# print('Performing Operations')
# print(operations)

# # user_list_service.get(operations)
# result = user_list_service.mutate(operations)
# user_list_id = result['value'][0]['id']

members = []
for d in names_control:
    members.append({
        'addressInfo': {
            'hashedFirstName': NormalizeAndSHA256(d['First Name']),
            'hashedLastName': NormalizeAndSHA256(d['Last Name']),
            'countryCode': 'US',
            'zipCode': d['ZIP']
        }
    })

mutate_members_operation = {
  'operand': {
      'userListId': 518989385,
      'membersList': members
  },
  'operator': 'ADD'
}

print('Starting list upload')
response = user_list_service.mutateMembers([mutate_members_operation])
print('Finished')

if 'userLists' in response:
    for user_list in response['userLists']:
        print('User list with name "%s" and ID "%d" was added.'
             % (user_list['name'], user_list['id']))


```

**Comment by jaehancrate** [comment] 2017-12-01 19:18
I was able to solve this by splitting the list (380k members) in two, then updating separately to the same audience list... I can close now. 

![image](https://user-images.githubusercontent.com/20776752/33499257-e4adbde2-d699-11e7-90d8-4560549849e7.png)

I can see that up to 1 million users can be added to the MutateMembersOperand ... but It wouldn't let me do so with 380k users (each with First name, last name, and zipcode) for the Customer Match program. 

Can anyone elaborate as to why I hit the limit? Thanks in advance!

**Comment by msaniscalchi** [comment] 2017-12-01 20:37
Hello Jae,

Thanks for the report! I don't think you hit the API limit, as you likely would have gotten back an actual error response from the API. Unfortunately, there's several possible explanations for the URLError you reported--e.g. it could be related to some network configuration or firewall that caused the connection to be terminated for this somewhat large request. I'll need to see if I can reproduce, but if you happen to have a firewall, perhaps you should check if disabling it temporarily has any impact.

Regards,
Mark

**Comment by jaehancrate** [comment] 2017-12-01 20:40
Hi Mark, 

No problem! So the weird thing is that I submitted this from home, and I don't have any firewalls that would prohibit this kind of thing... Maybe it's due to my network config -- but I am not well versed on networking so it's been hard for me to debug. 

It happened to work when I split the file -- so maybe that could point to something useful? 

Thanks for looking into this!

Jae

**Comment by msaniscalchi** [comment] 2018-02-15 23:26
Just leaving some notes, as I've been recently looking into this.

I've been able to reproduce this on a Windows environment. A full stacktrace looks like:

```
Traceback (most recent call last):
  File "add_crm_based_user_list_issue_241.py", line 131, in <module>
    main(adwords_client)
  File "add_crm_based_user_list_issue_241.py", line 108, in main
    response = user_list_service.mutateMembers([mutate_members_operation])
  File "C:\Users\msaniscalchi\py2env\lib\site-packages\googleads\common.py", line 780, in MakeSoapRequest
    return soap_service_method(*packed_contents)
  File "C:\Users\msaniscalchi\py2env\lib\site-packages\suds\client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "C:\Users\msaniscalchi\py2env\lib\site-packages\suds\client.py", line 584, in invoke
    result = self.send(soapenv)
  File "C:\Users\msaniscalchi\py2env\lib\site-packages\suds\client.py", line 625, in send
    reply = self.options.transport.send(request)
  File "C:\Users\msaniscalchi\py2env\lib\site-packages\googleads\util.py", line 123, in PatchedHttpTransportSend
    fp = self.u2open(u2request)
  File "C:\Users\msaniscalchi\py2env\lib\site-packages\suds\transport\http.py", line 132, in u2open
    return url.open(u2request, timeout=tm)
  File "C:\Python27\Lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\Lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\Lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\Lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\Lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10053] An established connection was aborted by the software in your host machine>
```

Unsurprisingly, the operation doesn't complete--the user list is not populated. My current impression is that this is some sort of timeout, but that is configured to 3600 seconds on our end. Looking through the suds-jurko code, it appears to just be calling an OpenerDirector instance's open method with a constructed request instance and configured timeout. It's not very clear whether the cause of the connection being closed is client-side (i.e. an issue with suds / urllib2) or server-side (i.e. an API issue).

**Comment by msaniscalchi** [comment] 2018-02-20 21:54
On further review, I don't believe this is a Python-specific issue. I have been able to reproduce on Java (on Windows) at 380k users. I'm escalating this to the AdWords team.

I'll leave this issue open for now for tracking purposes.

**Comment by msaniscalchi** [comment] 2018-03-06 20:07
I've been informed that this has been resolved, and have verified that requests up to the suggested maximum should now work. I'll be closing this now, feel free to let me know if there are still issues relating to this.

**Closed by msaniscalchi** 2018-03-06 20:07 UTC

**Comment by jaehancrate** [comment] 2018-03-06 20:16
Thank you!

*Jae Han*
Marketing Automation Developer,
Marketing Automation and Technology Management


1250 Techny Road
Northbrook, IL 60062
W (847) 239-6659
M (317) 219-9758

This email and any attachments may contain information that is privileged,
confidential and/or subject to attorney/client privilege, attorney work
product, intellectual property or other protections. If you have received
this email in error, please delete the message and any attachments and
notify the sender immediately. Please do not disseminate, copy or
distribute this information.
