### ISSUE TITLE
Disable envelope logging as INFO by default

### ISSUE THREAD

**Issue by andreycizov** [googleads/googleads-python-lib#262] opened 2018-03-22 18:30 UTC
All request envelopes are by default logged at the INFO level therefore breaking any sorts of logic behind logging levels. I generally work with envelopes of at least the maximum allowed for an API call and it starts spamming the console immediately.

```
[2018-03-22 18:26:41,363][INFO][googleads.common]	SOAP response:
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Header>
      <ResponseHeader xmlns="https://adwords.google.com/api/adwords/cm/v201802">
         <requestId>0005680472f286c00a37154359045a59</requestId>
         <serviceName>AdGroupCriterionService</serviceName>
         <methodName>mutateLabel</methodName>
         <operations>10</operations>
         <responseTime>66</responseTime>
      </ResponseHeader>
```

**Comment by msaniscalchi** [comment] 2018-03-22 19:27
Hello,

Thanks for the report! This behavior is technically working as intended in the sense that this behavior has been standardized across the client libraries. Although, I can forward your feedback along to the wider team and see if a case can be made for some changes.

Some additional information may help me be helpful. Why specifically is the INFO level problematic for logging this information? What would you expect to be logged at the INFO level instead? What would the recommended alternative be for logging this information, and why would that be an improvement?

Regards,
Mark

**Comment by andreycizov** [comment] 2018-03-23 17:20
Hello,

The expected behaviour is for the envelopes to be logged when the logging level is DEBUG. 

For example, the suds library that is used by googleads would only log the envelopes of requests if it's logging level is set to DEBUG. The same is true for a popular python library called requests.

I would like to also note that while the default logging level in python is WARNING, both suds and requests libraries would still not log the envelopes of the requests, but only the meta information, for example "INFO: Sending request: GET www.google.com".

One of the reasons why this is an issue is that sometimes you'd just want to see that the requests are happening, but not the requests themselves. It's also not the expected behaviour as I have just shown.

Thanks,
Andrey

**Comment by msaniscalchi** [comment] 2018-03-29 13:45
Hello Andrey,

As an FYI, we agree that logging successful request's SOAP envelopes at the INFO level is not ideal. We'll be updating the library to log these messages at the DEBUG level in a future release. In the meantime, I'll keep this issue open for tracking purposes.

Regards,
Mark

**Comment by msaniscalchi** [comment] 2018-05-03 17:58
This will be resolved alongside the upcoming DFP release.

Also worth noting, the Zeep SOAP client option (which is the default following 11.0.0) already currently logs the response envelope at the DEBUG level.

**Comment by msaniscalchi** [comment] 2018-05-17 15:16
This was fixed in the last release.

**Closed by msaniscalchi** 2018-05-17 15:16 UTC
Labels: P2, enhancement
