### ISSUE TITLE
Sitelinks batch operation

### ISSUE THREAD

**Issue by howach** [googleads/googleads-python-lib#158] opened 2016-10-24 17:14 UTC
I want to upload sitelinks in bulk and see that it's supported by BatchJobService (AdGroupExtensionSettingOperation) here: https://developers.google.com/adwords/api/docs/guides/batch-jobs#supported_operations

But when I try to find AdGroupExtensionSettingOperation in the _OPERATION_MAP dictionary here https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py I can’t find it. Am I missing anything?

Thanks,
Peter

**Comment by msaniscalchi** [comment] 2016-10-24 17:24
Hello,

Thanks for the report! No, it looks like the issue is on our end. I'll have this resolved in a nearby release.

Regards,
Mark

**Closed** 2016-12-07 22:41 UTC
