### ISSUE TITLE
Response Error

### ISSUE THREAD

**Issue by dripti** [googleads/googleads-python-lib#328] opened 2018-09-24 09:58 UTC
Hi I am getting the below error, I have tried changing the client secret and refresh token as well. 
Does anyone has an idea about it?

packages\google\oauth2\_client.py", line 61, in _handle_error_response
    error_details, response_body)

RefreshError: ('invalid_client: Unauthorized', '{\n  "error" : "invalid_client",\n  "error_description" : "Unauthorized"\n}')

**Comment by dripti** [comment] 2018-09-24 16:11
yes i am configuring with googleads.yaml file, and already done with all the steps. tried these steps 3 - 4 times.

**Comment by msaniscalchi** [comment] 2018-09-24 19:51
O.K. I'm unable to reproduce on my end, as I'm able to get past the refresh step and make API calls. The error you're reporting suggests this happens during the [refresh step](https://developers.google.com/identity/protocols/OAuth2WebServer#offline), which is used to produce a new access token using the refresh token you specified. Did this previously work?

Based on the error message, I suspect something must have went wrong during the authorization step. Have you tried running the [generate_refresh_token.py](https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/authentication/generate_refresh_token.py) example to obtain your **refresh token**? I want to verify whether anything unusual happens during the authorization step. Finally, on receiving a new `refresh_token` from that example, I'd like to see if providing that in your configuration file instead makes any difference.

Regards,
Mark

**Comment by msaniscalchi** [comment] 2018-09-27 14:14
Hello,

The [CUSTOMER_SERVING_TYPE_REPORT_MISMATCH](https://developers.google.com/adwords/api/docs/common-errors#ReportDefinitionError.CUSTOMER_SERVING_TYPE_REPORT_MISMATCH) error is typically seen when one attempts to run a report against a manager account. You'll need to specify a non-manager account to run the report against.

Regards,
Mark

**Comment by nikhilalmeida** [comment] 2018-09-27 22:08
Hi,
On running the `generate_refresh_token.py`,  get back an 'Access Token' and a 'Refresh Token'.
Do we need to set up the access token anywhere.
The `googleads.yaml` file has no provisions for configuring the Access Token. Only the refresh token.

I end up getting the following error.
```
[2018-09-27 15:06:16,581 - googleads.soap - WARNING] Error summary: {'faultMessage': "[AuthenticationError.OAUTH_TOKEN_INVALID @ ; trigger:'<null>']", 'requestId': '000576e18c42f5d80a62cf06fa038240', 'serviceName': 'CampaignService', 'methodName': 'get', 'operations': '1', 'responseTime': '75'}
...
GoogleAdsServerFault: [AuthenticationError.OAUTH_TOKEN_INVALID @ ; trigger:'<null>']
```

**Comment by msaniscalchi** [comment] 2018-09-28 14:05
> Do we need to set up the access token anywhere?

No, but you could use it with a [`GoogleAccessTokenClient`](https://github.com/googleads/googleads-python-lib/blob/master/googleads/oauth2.py#L95), or any other client that takes an `access_token` argument.

> The googleads.yaml file has no provisions for configuring the Access Token. Only the refresh token.

This was an intentional decision based on the short lifespan of access tokens. For use-cases where you need to frequently juggle access tokens between different clients, `LoadFromStorage` or `LoadFromString` are not ideal. You should instead instantiate an `AdWordsClient` and specify the `GoogleOAuth2Client` implementation that best suits your needs.

Regards,
Mark

**Comment by dripti** [comment] 2018-09-28 15:35
Hi Mark, 

Customer client id would be the account id and not the mcc id ? what if i have 100 accounts in 1 mcc and i need to get the video reports for all of these. How would it work?

**Comment by wihl** [comment] 2019-04-15 13:21
Closed as "solution offered"

**Closed by wihl** 2019-04-15 13:21 UTC

**Comment by noelpuru** [comment] 2019-12-10 20:15
@nikhilalmeida , did you manage to resolve your issue? I'm getting the same problem.

**Comment by poojitha-gandra25** [comment] 2021-12-11 00:21
Hi I am seeing this as an error in warning message. I am looping over all the accounts and i 
 i can see data in my downloaded report. I believe it is just not retrieving any data for the below manager account and showing it as a warning ! 

 {bash_operator.py:157} INFO - WARNING:googleads.adwords.report_downloader:Request Summary: {'clientCustomerId': '******', 'includeZeroImpressions': 'False', 'server': 'adwords.google.com', 'skipColumnHeader': 'True', 'skipReportHeader': 'True', 'skipReportSummary': 'True', 'isError': True, 'errorMessage': '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><reportDownloadError><ApiError><type>ReportDefinitionError.CUSTOMER_SERVING_TYPE_REPORT_MISMATCH</type><trigger></trigger><fieldPath>selector.reportDefinition</fieldPath></ApiError></reportDownloadError>'}
