### ISSUE TITLE
Cannot comment on github issues

### ISSUE THREAD

**Issue by apurvis** [googleads/googleads-python-lib#353] opened 2018-11-21 07:03 UTC
@msaniscalchi something about the configuration means i cannot comment on any github issues, only create new ones.  Can you fix that?
<img width="715" alt="screen shot 2018-11-21 at 2 02 19 am" src="https://user-images.githubusercontent.com/231694/48824189-8710b680-ed31-11e8-8b11-cefba34419a5.png">

following up on https://github.com/googleads/googleads-python-lib/issues/352 - if i wanted to use the Google Ads (not adwords) API and use an MCC account, what kind of authorization do i need to setup?

**Comment by wihl** [comment] 2019-04-15 13:29
Duplicate of [Google Ads API #77](https://github.com/googleads/google-ads-python/issues/77) and #352

**Closed by wihl** 2019-04-15 13:29 UTC
