### ISSUE TITLE
 not well-formed (invalid token) 

### ISSUE THREAD

**Issue by aisir** [googleads/googleads-python-lib#239] opened 2017-11-23 09:04 UTC
Hi,
    I'm using service   ManagedCustomerService.get(default_selector)
get following info ,checking it find that because of the '\x08' in my client_customerName :
[mid201]_CleanMaster\x08B
[mid201]\x08Battery Pro

please note to check

 File "/home/aisir/aws/adcaptain-data-google/adwordslib/services.py", line 43, in get_items_cursor
    page = obj_service.get(default_selector)
  File "/usr/local/lib/python3.6/dist-packages/googleads/common.py", line 753, in MakeSoapRequest
    self._datetime_packer) for arg in args])
  File "/usr/local/lib/python3.6/dist-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/python3.6/dist-packages/suds/client.py", line 621, in send
    original_soapenv=original_soapenv)
  File "/usr/local/lib/python3.6/dist-packages/suds/client.py", line 661, in process_reply
    replyroot = _parse(reply)
  File "/usr/local/lib/python3.6/dist-packages/suds/client.py", line 832, in _parse
    return Parser().parse(string=string)
  File "/usr/local/lib/python3.6/dist-packages/suds/sax/parser.py", line 133, in parse
    sax.parse(source)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python3.6/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:5034: not well-formed (invalid token)

**Comment by dklimkin** [comment] 2017-11-23 10:45
@aisir I am curios how did this happen -- backspace in the customer name?

Thanks for reporting, we'll look how this can be handled better.

**Comment by msaniscalchi** [comment] 2017-11-27 15:14
@dklimkin 
I'd argue that the library is working as intended when it fails to parse XML containing characters that are out of [range](https://www.w3.org/TR/xml/#charsets) for the specification. I don't think we should make any exceptions, as that would just mask the underlying issue of fields successfully being set to values containing invalid characters.

I'm pretty confident this is not a client-library specific issue, as it sounds like there is validation missing somewhere that allowed this control character to be set for the customer name. Of course, determining where that customer name was set would help us resolve the issue. :-)

@aisir 
To fix this particular issue for you, the control character will need to be removed from any affected customer names. That's not something I can do on the issue tracker for this library, but the [AdWords API Support Forum](https://groups.google.com/forum/#!forum/adwords-api) should be able to help with this.

**Comment by msaniscalchi** [comment] 2018-01-09 15:25
Closing this issue because the root cause is unrelated to this library. However, feel free to reopen if there's more I can help with.

**Closed by msaniscalchi** 2018-01-09 15:25 UTC
